import type { Metadata } from "next"
import { Roboto_Slab } from "next/font/google"
import "./globals.css"
import { Providers } from "./(Providers)/providers"
import { Header } from "./(Layout)/header/header"

const inter = Roboto_Slab({ subsets: ["latin", "cyrillic"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="layout">
            <Header />
            <div className="dark">{children}</div>
            <div>footer</div>
          </div>
        </Providers>
      </body>
    </html>
  )
}
